name: fearGod
options:
  bundleIdPrefix: com.assiamah
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16"

settings:
  base:
    DEVELOPMENT_TEAM: QGMAWHX827
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: "3.0.0"
    CURRENT_PROJECT_VERSION: "3"
    PRODUCT_BUNDLE_IDENTIFIER: com.assiamah.fearGod

targets:
  fearGod:
    type: application
    platform: iOS
    sources:
      - fearGod
    resources:
      - fearGod/Resources
    settings:
      base:
        PRODUCT_NAME: "Twi Bible"
        INFOPLIST_FILE: fearGod/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: fearGod/Info.plist
      properties:
        CFBundleName: Twi Bible
        CFBundleDisplayName: Twi Bible
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
